- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter username
    private: false # user can see what they are entering
  - name: PASSWORD
    prompt: please enter password
    private: true # user can't see what they are entering
  tasks:
  - name: print and check the values
    ansible.builtin.debug:
      msg: "username is {{USERNAME}}, password is {{PASSWORD}}"